language: android
before_install:
  - chmod +x gradlew
android:
  components:
    - tools
    - build-tools-24.0.1
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-24
    - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
  - linux
